runroom_samples.home:
    path: /
    controller: Runroom\RenderEventBundle\Controller\TemplateController
    defaults:
        template: '@RunroomSamples/home.html.twig'

# BasicEntities
runroom_samples.basic_entities.books:
    path: /books
    controller: Runroom\SamplesBundle\BasicEntities\Controller\BookController::books

runroom_samples.basic_entities.book:
    path: /book/{slug}
    controller: Runroom\SamplesBundle\BasicEntities\Controller\BookController::book

# Forms
runroom_samples.forms.contact:
    path: /contact
    controller: Runroom\SamplesBundle\Forms\Controller\ContactController::contact

runroom_samples.forms.contact_ajax:
    path: /contact-ajax
    methods: [GET]
    controller: Runroom\SamplesBundle\Forms\Controller\ContactController::contactAjax

runroom_samples.forms.contact_ajax_post:
    path: /contact-ajax
    methods: [POST]
    controller: Runroom\SamplesBundle\Forms\Controller\ContactController::contactAjaxPost

runroom_samples.forms.hubspot:
    path: /hubspot
    controller: Runroom\SamplesBundle\Forms\Controller\ContactController::hubspot
